### ISSUE TITLE
build fails when patched module is not in the project

### ISSUE THREAD

**Issue by davidverholen** [magento/magento-cloud-patches#51]
If a module is not installed (by composer replace configuration) and a patch exists for it, the whole build fails. In our example, we have not installed all the 3rd party modules from amazon, because we simply do not need them

### Preconditions

1. Magento 2.3.5-p1
2. magento/magento-cloud-patches 1.0.4

### Steps to reproduce

1. use composer replace to not install amazon 3rd party modules
2. deploy to cloud (or try to apply patches)

replace in composer.json:
```
"amzn/amazon-pay-sdk-php": "*",
"amzn/amazon-pay-and-login-with-amazon-core-module": "*",
"amzn/login-with-amazon-module": "*",
"amzn/amazon-pay-module": "*",
```
### Expected result

1. build is working

### Actual result

1. mutliple errors, all related to one Patch File:

example:

```
W:     Error Output:
    W:
    W:     ================
    W:
    W:     error: vendor/amzn/amazon-pay-module/Model/OrderInformationManagement.php
    W:   :
    W:     No such file or directory
    W:
    W:     error: vendor/amzn/amazon-pay-module/Plugin/ConfirmOrderReference.php: No
    W:    s
    W:     uch file or directory
    W:
    W:     error: vendor/amzn/amazon-pay-module/view/frontend/web/js/action/place-or
    W:   de
    W:     r.js: No such file or directory
    W:
    W:
    W:
    W:
    W:   apply [--git-installation [GIT-INSTALLATION]]
    W:
    W:
    W: In Shell.php line 86:
    W:
    W:   The command "php ./vendor/bin/ece-patches apply" failed. In Applier.php lin
    W:   e 140:
    W:
    W:
    W:     The command "'git' 'apply' '--check' '--reverse' '/app/vendor/magento/mag
    W:   en
    W:     to-cloud-patches/patches/BUNDLE-2554__set_payment_info_bug_fix__3.4.1.pat
    W:   ch
    W:     '" failed.
    W:
    W:
    W:
    W:     Exit Code: 1(General error)
```

suggestion:
let failed patches just fail, or check if the file(s) / the module exist before applying

**Comment by YPyltiai** [comment]
@davidverholen did you add replace directive to the root composer.json or anywhere else?

**Comment by davidverholen** [comment]
@YPyltiai to the root composer.json

**Comment by BarnyShergold** [comment]
@davidverholen @YPyltiai 
The problem seems to be that the Amazon modules have not been properly removed.

The full removal -
`"amzn/amazon-pay-and-login-magento-2-module": "*"`

This does the whole thing.

If a module is fully removed then patches are not applied. So I don't think there is a bug here and this issue could be closed?

**Comment by davidverholen** [comment]
you're right, that worked
